// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./clientWrapper"; // Import a client-side wrapper
import StoreProvider from "./redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap everything requiring client-side context inside ClientWrapper */}
        <StoreProvider>
          <ClientWrapper>{children}</ClientWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
